# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Carta')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_photos/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_card', to='api.Country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Expansión',
                'verbose_name_plural': 'Expansiones',
            },
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='expansion_photos/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Expansión',
                'verbose_name_plural': 'Expansiones',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='postalcode',
            name='city',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_extended',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='PostalCode',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='UserExtended',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
