# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171224_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha del envío')),
                ('type_shipping', models.IntegerField(blank=True, choices=[(0, 'PURCHASE'), (1, 'SALE')], default=0, null=True, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Carta', 'verbose_name_plural': 'Cartas'},
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='country_photos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='card',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_card', to='api.Shipping', verbose_name='Envío'),
        ),
    ]
