# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171225_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='type_shipping',
            new_name='shipping_type',
        ),
    ]
