# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180107_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_costs',
            field=models.FloatField(blank=True, null=True, verbose_name='Costes de envio'),
        ),
    ]
