# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180118_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansion_card', to='api.Expansion', verbose_name='Expansión'),
        ),
    ]
