# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_card_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_shipping', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='card',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_card', to='api.Country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expansion_card', to='api.Expansion', verbose_name='Expansión'),
        ),
        migrations.AlterField(
            model_name='card',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_card', to='api.Shipping', verbose_name='Envío'),
        ),
    ]
