# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-21 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180121_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_costs',
            new_name='costs',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_type',
            new_name='type',
        ),
    ]
